# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'form.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Widget(object):
    def setupUi(self, Widget):
        Widget.setObjectName("Widget")
        Widget.resize(797, 616)
        Widget.setMouseTracking(False)
        self.lblSalida = QtWidgets.QLabel(Widget)
        self.lblSalida.setGeometry(QtCore.QRect(40, 390, 631, 31))
        font = QtGui.QFont()
        font.setFamily("8514oem")
        font.setPointSize(20)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.lblSalida.setFont(font)
        self.lblSalida.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.lblSalida.setAcceptDrops(False)
        self.lblSalida.setAutoFillBackground(False)
        self.lblSalida.setStyleSheet("color: rgb(0, 0, 0);\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(185, 161, 255, 255), stop:1 rgba(255, 255, 255, 255));\n"
"font: 20pt \"8514oem\";\n"
"padding-left: 3px;\n"
"padding-bottom: 2px;\n"
"border:2px solid;\n"
"border-radius: 8px")
        self.lblSalida.setObjectName("lblSalida")
        self.TXTpWD = QtWidgets.QLineEdit(Widget)
        self.TXTpWD.setGeometry(QtCore.QRect(40, 110, 721, 71))
        font = QtGui.QFont()
        font.setFamily("MS Serif")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.TXTpWD.setFont(font)
        self.TXTpWD.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(185, 161, 255, 255), stop:1 rgba(255, 255, 255, 255));\n"
"padding-left: 5px;\n"
"border: 2px solid;\n"
"border-radius: 20px;")
        self.TXTpWD.setObjectName("TXTpWD")
        self.btnPwd = QtWidgets.QPushButton(Widget)
        self.btnPwd.setGeometry(QtCore.QRect(230, 230, 331, 51))
        font = QtGui.QFont()
        font.setFamily("MS Serif")
        font.setPointSize(16)
        font.setBold(False)
        font.setWeight(50)
        self.btnPwd.setFont(font)
        self.btnPwd.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(185, 161, 255, 255), stop:1 rgba(255, 255, 255, 255));\n"
"border: 2px solid;\n"
"border-radius: 10px;")
        self.btnPwd.setObjectName("btnPwd")
        self.lblSalida_2 = QtWidgets.QLabel(Widget)
        self.lblSalida_2.setGeometry(QtCore.QRect(200, 470, 391, 61))
        font = QtGui.QFont()
        font.setFamily("8514oem")
        font.setPointSize(18)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.lblSalida_2.setFont(font)
        self.lblSalida_2.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.lblSalida_2.setAcceptDrops(False)
        self.lblSalida_2.setStyleSheet("color: rgb(24,218, 33);\n"
"font: 18pt \"8514oem\";")
        self.lblSalida_2.setObjectName("lblSalida_2")

        self.retranslateUi(Widget)
        QtCore.QMetaObject.connectSlotsByName(Widget)

    def retranslateUi(self, Widget):
        _translate = QtCore.QCoreApplication.translate
        Widget.setWindowTitle(_translate("Widget", "Widget"))
        self.lblSalida.setText(_translate("Widget", "TextoPrueba"))
        self.btnPwd.setText(_translate("Widget", "CONVERTIR A EMOJI"))
        self.lblSalida_2.setText(_translate("Widget", "Info"))